# Generated by Django 5.2.6 on 2025-11-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_player1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_player2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='core.participant'),
        ),
    ]
